name: Build VM Disk Image

on:
  push:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Find snapshot variables
        run: |
          bash create_vars.sh
          echo "SNAP_SUM=$(cat checksum)" >> $GITHUB_ENV

      - name: Cache OpenBSD-current qcow2
        id: openbsd-current
        uses: actions/cache@v3
        with:
          path: output
          key: ${{ env.SNAP_SUM }}-output

      - name: Install Dependecies
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt -y install curl unzip qemu-system-x86

      - name: Copy UEFI
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: cp /usr/share/ovmf/OVMF.fd .

      - name: Install Packer
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: |
          curl -o packer.zip -L https://releases.hashicorp.com/packer/${PVER}/packer_${PVER}_linux_amd64.zip
          unzip packer.zip
          mv packer /usr/local/bin
        env:
          PVER: 1.8.1

      - name: Validate Packer Template
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: |
          packer validate -syntax-only -var-file=openbsd.pkrvars.hcl openbsd.pkr.hcl

      - name: Build Packer Image
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: |
          packer build -on-error=abort -var-file=openbsd.pkrvars.hcl openbsd.pkr.hcl
        env:
          PACKER_LOG: 1

      - name: Create qcow2 signature
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: |
          sha256sum output/openbsd-snapshots-x86_64.qcow2 > output/openbsd-snapshots-x86_64.sig

      - name: Copy root password
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        run: |
          cp root_password output/

      - name: Create current release
        if: steps.openbsd-current.outputs.cache-hit != 'true'
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: current
          files:
            output/openbsd-snapshots-x86_64.qcow2
            output/openbsd-snapshots-x86_64.sig
            output/root_password
